"""add previous submission id to assignments

Revision ID: fa118b5fef05
Revises: dc7a0dcbf5f9
Create Date: 2026-06-23 12:31:43.068467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa118b5fef05'
down_revision: Union[str, Sequence[str], None] = 'dc7a0dcbf5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('previous_submission_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'previous_submission_id')
    # ### end Alembic commands ###
